sonar.projectKey=Vedanshu7_llmbridge
sonar.organization=vedanshu7
sonar.projectName=llmbridge
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
