apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llmbridge.fullname" . }}-config
  labels:
    {{- include "llmbridge.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config | nindent 4 }}
